[package]
name = "cmajor-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
cmajor-core = { workspace = true }
proc-macro2 = { version = "1.0.95", features = ["span-locations"] }
quote = "1.0.40"
syn = "2.0.104"

[dev-dependencies]
cmajor = { workspace = true }
